//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApplication
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int mygradient = 2130837505;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int Clock = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int RefreshButton = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int gradient0 = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int helloLabel = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int sensor2 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int sensor3 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int sensor4 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int sensor5 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int sensor6 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int sensor7 = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int widget39 = 2131034112;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int helloLabelText = 2130968578;
			
			private String()
			{
			}
		}
	}
}
