//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoveUpApp
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btnBackground_elephant = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btnBackground_giraffe = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btnBackground_tiger = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btnBackground_zebra = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int elephants_fr = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int elephants_fr_klein = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int giraffe_fr = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int giraffe_fr_klein = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int littlezebra = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int tiger_fr = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int tiger_fr_klein = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int verticalgradient = 2130837516;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int MooveBtn1 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int MooveBtn2 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int MooveBtn3 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int MooveBtn4 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int gradient0 = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int layout0 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int widget39 = 2131099649;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Giraffe = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int air = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int M77_Bombay_Street_Up_In_The_Sky = 2130968577;
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int local_service_started = 2131034114;
			
			private String()
			{
			}
		}
	}
}
